### PR TITLE
Fix unlimited db errors

### PR DESCRIPTION
**Pull request by Arnoldosmium**
By reset and rerun migrations

### CODE REVIEW

**Comment by Arnoldosmium** [comment]
Checking the CI log, it is obvious that some models have incorrect syntax. Feel free to merge and ci check should be g2g from now on

**Comment by jiashenC** [comment]
I think `python manage.py test` runs on the `test` database instead of `mediconnect` which is supposed to be for production.

**Comment by Arnoldosmium** [comment]
the test database will be created as test runtime and named as `test_mediconnect`
in order to run `makemigration` to [check model errors](https://travis-ci.org/mediconnect/backend/builds/404730772#L651), `mediconnect` table is [necessary](https://travis-ci.org/mediconnect/backend/builds/404730307#L645).

**Comment by jiashenC** [comment]
I see, my bad. Looks good to me.

**Review by jiashenC — APPROVED** [review]

**Comment by Arnoldosmium** [comment]
Flup:
@gabrielwry please check the [`hospital` related errors](https://travis-ci.org/mediconnect/backend/builds/404730772#L637).

@jiashenC please double check the local vs on ci check server MySQL and python versions

**Pull request merged**
